import {MigrationInterface, QueryRunner} from "typeorm";

export class InitialSetup1591549886422 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "role" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "businessId" uuid, CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_user" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "roleId" uuid, CONSTRAINT "REL_2a23ceb75c7511d0523c4aaf49" UNIQUE ("userId"), CONSTRAINT "REL_89e55dae19555d0d5fe8602b28" UNIQUE ("roleId"), CONSTRAINT "PK_e3583d40265174efd29754a7c57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "application_route" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" character varying NOT NULL, "description" character varying NOT NULL, "type" integer NOT NULL, CONSTRAINT "PK_67f2c7f0076c385064ff999c572" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_premission" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicationrouteId" uuid, "userId" uuid, CONSTRAINT "PK_3e3e1285eceb06bdae73d70564c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "email" character varying NOT NULL, "emailConfirmed" boolean NOT NULL, "password" character varying NOT NULL, "twoFactorEnable" boolean NOT NULL, "accessFailedCount" integer NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "isDisabled" boolean NOT NULL, "phonenumber" character varying NOT NULL, "businessId" uuid, CONSTRAINT "REL_78725ac7117e7526e028014606" UNIQUE ("businessId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sales" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" uuid, "businesslocationId" uuid, CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3a92cf6add00043cef9833db1c" ON "sales" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb98ebb1d41a945ac43aa75d9f" ON "sales" ("businesslocationId") `);
        await queryRunner.query(`CREATE TABLE "customer" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fullname" character varying NOT NULL, "mobilenumber" character varying NOT NULL, "email" character varying NOT NULL, "gender" integer NOT NULL, "age" integer NOT NULL, "birthday" integer NOT NULL, "birthmonth" character varying NOT NULL, "businesslocationId" uuid, CONSTRAINT "PK_a7a13f4cacb744524e44dfdad32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "supplier" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyname" character varying NOT NULL, "mobilenumber" character varying NOT NULL, "email" character varying NOT NULL, "address" character varying NOT NULL, "businesslocationId" uuid, CONSTRAINT "PK_2bc0d2cab6276144d2ff98a2828" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceNumber" character varying NOT NULL, "orderstatus" integer NOT NULL, "totalcostprice" integer NOT NULL, "businesslocationId" uuid, "supplierId" uuid, CONSTRAINT "PK_1031171c13130102495201e3e20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_item" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "qty" integer NOT NULL, "cost" integer NOT NULL, "unitprice" integer NOT NULL, "previousqty" integer NOT NULL, "productId" uuid, "orderId" uuid, CONSTRAINT "PK_d01158fe15b1ead5c26fd7f4e90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_payment" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "paymenttype" character varying NOT NULL, "paymentdate" character varying NOT NULL, "amountpaid" integer NOT NULL, "balnce" integer NOT NULL, "orderId" uuid, CONSTRAINT "PK_28c756d4fd41223fedfbd2750e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_card" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "StockMovementDescription" character varying NOT NULL, "Direction" integer NOT NULL, "Quantity" integer NOT NULL, "businesslocationId" uuid, "productId" uuid, CONSTRAINT "PK_4fbf097977601f59e44eb7e418f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fc8fa788a8128a0c6c01f3e79d" ON "stock_card" ("businesslocationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_023e24d32b48071bda0f9bc5af" ON "stock_card" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_831a09ba37eecc411d560f2e17" ON "stock_card" ("Direction") `);
        await queryRunner.query(`CREATE INDEX "IDX_93bd7d26e1de63240900871503" ON "stock_card" ("Quantity") `);
        await queryRunner.query(`CREATE TABLE "store_product" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "instockqty" integer NOT NULL, "committedqty" integer NOT NULL, "orderedqty" integer NOT NULL, "availableqty" integer NOT NULL, "businesslocationId" uuid, "productId" uuid, CONSTRAINT "PK_de6af3a8762c59860794f42d8f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ba44c296693b083792742c73c5" ON "store_product" ("businesslocationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_13e275149d7414c2694da12dcf" ON "store_product" ("productId") `);
        await queryRunner.query(`CREATE TABLE "product_configuration" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pack" integer NOT NULL, "leadtime" integer NOT NULL, "canexpire" boolean NOT NULL, "canbesold" boolean NOT NULL, "canbepurchased" boolean NOT NULL, "anypromo" boolean NOT NULL, "productId" uuid, CONSTRAINT "REL_dd60910c632f58d804c029e03a" UNIQUE ("productId"), CONSTRAINT "PK_234f05214d60c49e9a673bd7e2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dd60910c632f58d804c029e03a" ON "product_configuration" ("productId") `);
        await queryRunner.query(`CREATE TABLE "price_configuration" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "qty" integer NOT NULL, "price" integer NOT NULL, "ispromo" boolean NOT NULL, "start" TIMESTAMP NOT NULL, "end" TIMESTAMP NOT NULL, "productId" uuid, CONSTRAINT "PK_cc0a28c08c385d20508c19d71cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b3beed5d4b57fd35b1dc80921b" ON "price_configuration" ("productId") `);
        await queryRunner.query(`CREATE TABLE "product" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "itemcode" character varying NOT NULL, "description" character varying NOT NULL, "imagelink" character varying NOT NULL, "categoryId" uuid, "subCategoryId" uuid, "businessId" uuid, "productconfigurationId" uuid, CONSTRAINT "REL_beb436344a3af6611cbfac22e7" UNIQUE ("productconfigurationId"), CONSTRAINT "PK_bebc9158e480b949565b4dc7a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22cc43e9a74d7498546e9a63e7" ON "product" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_a47bd591fe7cf05bec0d88a679" ON "product" ("itemcode") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff0c0301a95e517153df97f681" ON "product" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b95800811275dd98a888044d5" ON "product" ("businessId") `);
        await queryRunner.query(`CREATE TABLE "category" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "businessId" uuid, CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sub_category" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "categoryId" uuid, "businessId" uuid, CONSTRAINT "PK_59f4461923255f1ce7fc5e7423c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_transfer" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transfertype" integer NOT NULL, "businesslocationFromId" uuid, "businesslocationToId" uuid, CONSTRAINT "PK_b6165ea3cc5b8062e7eaa1bd44d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6897e007b1f7d24060183c457c" ON "stock_transfer" ("transfertype") `);
        await queryRunner.query(`CREATE INDEX "IDX_b48373f86aa3a9375fba0763d7" ON "stock_transfer" ("businesslocationFromId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b7e00f224d2baaaa80bad4454" ON "stock_transfer" ("businesslocationToId") `);
        await queryRunner.query(`CREATE TABLE "business" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "address" character varying NOT NULL, "logoPath" character varying NOT NULL, CONSTRAINT "PK_0bd850da8dafab992e2e9b058e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "business_location" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "address" character varying NOT NULL, "businessId" uuid, CONSTRAINT "PK_3288cfb92c9598363f830e1a56b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "business_location_user" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying NOT NULL, "updatedby" character varying NOT NULL, "IsActive" boolean NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businesslocationId" uuid, "userId" uuid, CONSTRAINT "PK_868d891a99a2d946bd2c01d2668" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unit_of_stock" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "PK_5960061921d6bbefcff53d4412d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "FK_29beacc87831d8b4f775e0c4057" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_user" ADD CONSTRAINT "FK_2a23ceb75c7511d0523c4aaf492" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_user" ADD CONSTRAINT "FK_89e55dae19555d0d5fe8602b281" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_premission" ADD CONSTRAINT "FK_11d81560c95f356256b89c0f27f" FOREIGN KEY ("applicationrouteId") REFERENCES "application_route"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_premission" ADD CONSTRAINT "FK_ac8e782ab0a27f3b545cdbf1bc5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_78725ac7117e7526e028014606b" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_3a92cf6add00043cef9833db1cd" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_bb98ebb1d41a945ac43aa75d9f4" FOREIGN KEY ("businesslocationId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "FK_0233f7239d820ca88cbf8271187" FOREIGN KEY ("businesslocationId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier" ADD CONSTRAINT "FK_3e709ce06a9e3ccd49d8c913bce" FOREIGN KEY ("businesslocationId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_8f70b98e1b4157e88dab5903592" FOREIGN KEY ("businesslocationId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_af5c3fc71f410fb94a613f6b66e" FOREIGN KEY ("supplierId") REFERENCES "supplier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_904370c093ceea4369659a3c810" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_payment" ADD CONSTRAINT "FK_8e5de5355bcad91a7769f16504c" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_card" ADD CONSTRAINT "FK_fc8fa788a8128a0c6c01f3e79d9" FOREIGN KEY ("businesslocationId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_card" ADD CONSTRAINT "FK_023e24d32b48071bda0f9bc5af3" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_product" ADD CONSTRAINT "FK_ba44c296693b083792742c73c51" FOREIGN KEY ("businesslocationId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_product" ADD CONSTRAINT "FK_13e275149d7414c2694da12dcf7" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_configuration" ADD CONSTRAINT "FK_dd60910c632f58d804c029e03a2" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_configuration" ADD CONSTRAINT "FK_b3beed5d4b57fd35b1dc80921bc" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_ff0c0301a95e517153df97f6812" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_463d24f6d4905c488bd509164e6" FOREIGN KEY ("subCategoryId") REFERENCES "sub_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_8b95800811275dd98a888044d50" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_beb436344a3af6611cbfac22e7b" FOREIGN KEY ("productconfigurationId") REFERENCES "product_configuration"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "FK_38a5797d0473710fb41af5a97f1" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sub_category" ADD CONSTRAINT "FK_51b8c0b349725210c4bd8b9b7a7" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sub_category" ADD CONSTRAINT "FK_99a26d343738525a71710e1b898" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" ADD CONSTRAINT "FK_b48373f86aa3a9375fba0763d76" FOREIGN KEY ("businesslocationFromId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" ADD CONSTRAINT "FK_3b7e00f224d2baaaa80bad4454a" FOREIGN KEY ("businesslocationToId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_location" ADD CONSTRAINT "FK_46df66863ec4dac6a3572765220" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_location_user" ADD CONSTRAINT "FK_81e8aa7e586ffc4862872288b7c" FOREIGN KEY ("businesslocationId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_location_user" ADD CONSTRAINT "FK_98fe6a097afff52cc681753147d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "business_location_user" DROP CONSTRAINT "FK_98fe6a097afff52cc681753147d"`);
        await queryRunner.query(`ALTER TABLE "business_location_user" DROP CONSTRAINT "FK_81e8aa7e586ffc4862872288b7c"`);
        await queryRunner.query(`ALTER TABLE "business_location" DROP CONSTRAINT "FK_46df66863ec4dac6a3572765220"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" DROP CONSTRAINT "FK_3b7e00f224d2baaaa80bad4454a"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" DROP CONSTRAINT "FK_b48373f86aa3a9375fba0763d76"`);
        await queryRunner.query(`ALTER TABLE "sub_category" DROP CONSTRAINT "FK_99a26d343738525a71710e1b898"`);
        await queryRunner.query(`ALTER TABLE "sub_category" DROP CONSTRAINT "FK_51b8c0b349725210c4bd8b9b7a7"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "FK_38a5797d0473710fb41af5a97f1"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_beb436344a3af6611cbfac22e7b"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_8b95800811275dd98a888044d50"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_463d24f6d4905c488bd509164e6"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_ff0c0301a95e517153df97f6812"`);
        await queryRunner.query(`ALTER TABLE "price_configuration" DROP CONSTRAINT "FK_b3beed5d4b57fd35b1dc80921bc"`);
        await queryRunner.query(`ALTER TABLE "product_configuration" DROP CONSTRAINT "FK_dd60910c632f58d804c029e03a2"`);
        await queryRunner.query(`ALTER TABLE "store_product" DROP CONSTRAINT "FK_13e275149d7414c2694da12dcf7"`);
        await queryRunner.query(`ALTER TABLE "store_product" DROP CONSTRAINT "FK_ba44c296693b083792742c73c51"`);
        await queryRunner.query(`ALTER TABLE "stock_card" DROP CONSTRAINT "FK_023e24d32b48071bda0f9bc5af3"`);
        await queryRunner.query(`ALTER TABLE "stock_card" DROP CONSTRAINT "FK_fc8fa788a8128a0c6c01f3e79d9"`);
        await queryRunner.query(`ALTER TABLE "order_payment" DROP CONSTRAINT "FK_8e5de5355bcad91a7769f16504c"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_904370c093ceea4369659a3c810"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_af5c3fc71f410fb94a613f6b66e"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_8f70b98e1b4157e88dab5903592"`);
        await queryRunner.query(`ALTER TABLE "supplier" DROP CONSTRAINT "FK_3e709ce06a9e3ccd49d8c913bce"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "FK_0233f7239d820ca88cbf8271187"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_bb98ebb1d41a945ac43aa75d9f4"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_3a92cf6add00043cef9833db1cd"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_78725ac7117e7526e028014606b"`);
        await queryRunner.query(`ALTER TABLE "user_premission" DROP CONSTRAINT "FK_ac8e782ab0a27f3b545cdbf1bc5"`);
        await queryRunner.query(`ALTER TABLE "user_premission" DROP CONSTRAINT "FK_11d81560c95f356256b89c0f27f"`);
        await queryRunner.query(`ALTER TABLE "role_user" DROP CONSTRAINT "FK_89e55dae19555d0d5fe8602b281"`);
        await queryRunner.query(`ALTER TABLE "role_user" DROP CONSTRAINT "FK_2a23ceb75c7511d0523c4aaf492"`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "FK_29beacc87831d8b4f775e0c4057"`);
        await queryRunner.query(`DROP TABLE "unit_of_stock"`);
        await queryRunner.query(`DROP TABLE "business_location_user"`);
        await queryRunner.query(`DROP TABLE "business_location"`);
        await queryRunner.query(`DROP TABLE "business"`);
        await queryRunner.query(`DROP INDEX "IDX_3b7e00f224d2baaaa80bad4454"`);
        await queryRunner.query(`DROP INDEX "IDX_b48373f86aa3a9375fba0763d7"`);
        await queryRunner.query(`DROP INDEX "IDX_6897e007b1f7d24060183c457c"`);
        await queryRunner.query(`DROP TABLE "stock_transfer"`);
        await queryRunner.query(`DROP TABLE "sub_category"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP INDEX "IDX_8b95800811275dd98a888044d5"`);
        await queryRunner.query(`DROP INDEX "IDX_ff0c0301a95e517153df97f681"`);
        await queryRunner.query(`DROP INDEX "IDX_a47bd591fe7cf05bec0d88a679"`);
        await queryRunner.query(`DROP INDEX "IDX_22cc43e9a74d7498546e9a63e7"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP INDEX "IDX_b3beed5d4b57fd35b1dc80921b"`);
        await queryRunner.query(`DROP TABLE "price_configuration"`);
        await queryRunner.query(`DROP INDEX "IDX_dd60910c632f58d804c029e03a"`);
        await queryRunner.query(`DROP TABLE "product_configuration"`);
        await queryRunner.query(`DROP INDEX "IDX_13e275149d7414c2694da12dcf"`);
        await queryRunner.query(`DROP INDEX "IDX_ba44c296693b083792742c73c5"`);
        await queryRunner.query(`DROP TABLE "store_product"`);
        await queryRunner.query(`DROP INDEX "IDX_93bd7d26e1de63240900871503"`);
        await queryRunner.query(`DROP INDEX "IDX_831a09ba37eecc411d560f2e17"`);
        await queryRunner.query(`DROP INDEX "IDX_023e24d32b48071bda0f9bc5af"`);
        await queryRunner.query(`DROP INDEX "IDX_fc8fa788a8128a0c6c01f3e79d"`);
        await queryRunner.query(`DROP TABLE "stock_card"`);
        await queryRunner.query(`DROP TABLE "order_payment"`);
        await queryRunner.query(`DROP TABLE "order_item"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`DROP TABLE "supplier"`);
        await queryRunner.query(`DROP TABLE "customer"`);
        await queryRunner.query(`DROP INDEX "IDX_bb98ebb1d41a945ac43aa75d9f"`);
        await queryRunner.query(`DROP INDEX "IDX_3a92cf6add00043cef9833db1c"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "user_premission"`);
        await queryRunner.query(`DROP TABLE "application_route"`);
        await queryRunner.query(`DROP TABLE "role_user"`);
        await queryRunner.query(`DROP TABLE "role"`);
    }

}
