import {MigrationInterface, QueryRunner} from "typeorm";

export class FinalScript1594649412598 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "role" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "businessId" uuid, CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_user" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "roleId" uuid, CONSTRAINT "REL_2a23ceb75c7511d0523c4aaf49" UNIQUE ("userId"), CONSTRAINT "REL_89e55dae19555d0d5fe8602b28" UNIQUE ("roleId"), CONSTRAINT "PK_e3583d40265174efd29754a7c57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "application_route" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "url" character varying NOT NULL, "description" character varying NOT NULL, "type" integer NOT NULL, CONSTRAINT "PK_67f2c7f0076c385064ff999c572" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_premission" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicationrouteId" uuid, "userId" uuid, CONSTRAINT "PK_3e3e1285eceb06bdae73d70564c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying(300) NOT NULL, "email" character varying(100) NOT NULL, "emailConfirmed" boolean NOT NULL DEFAULT false, "password" character varying(300) NOT NULL, "twoFactorEnable" boolean NOT NULL DEFAULT false, "accessFailedCount" integer NOT NULL DEFAULT 0, "userType" integer NOT NULL DEFAULT 3, "firstName" character varying(300) NOT NULL, "lastName" character varying NOT NULL, "siguptoken" character varying(300), "phonenumber" character varying(15) NOT NULL, "businessId" uuid, "businesslocationId" uuid, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sales" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" uuid, "businesslocationId" uuid, CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3a92cf6add00043cef9833db1c" ON "sales" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb98ebb1d41a945ac43aa75d9f" ON "sales" ("businesslocationId") `);
        await queryRunner.query(`CREATE TABLE "customer" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fullname" character varying NOT NULL, "mobilenumber" character varying NOT NULL, "email" character varying NOT NULL, "gender" integer NOT NULL, "age" integer NOT NULL, "birthday" integer NOT NULL, "birthmonth" character varying NOT NULL, "businesslocationId" uuid, CONSTRAINT "PK_a7a13f4cacb744524e44dfdad32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "supplier" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "companyname" character varying NOT NULL, "mobilenumber" character varying NOT NULL, "email" character varying NOT NULL, "address" character varying NOT NULL, "website" character varying NOT NULL, "contactpersonname" character varying NOT NULL, "contactpersonphonenumber" character varying NOT NULL, "contactpersonemail" character varying NOT NULL, "street" character varying NOT NULL, "facebook" character varying NOT NULL, "instagram" character varying NOT NULL, "twitter" character varying NOT NULL, "businessId" uuid, "registeredlocationId" uuid, CONSTRAINT "PK_2bc0d2cab6276144d2ff98a2828" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fiscal_year" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "startdate" TIMESTAMP NOT NULL, "enddate" TIMESTAMP NOT NULL, "iscurrent" boolean NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_72fa5ea3e6b0ec7542c23bf0389" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_order_payment" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "paymenttype" character varying NOT NULL, "paymentdate" character varying NOT NULL, "amountpaid" integer NOT NULL, "balnce" integer NOT NULL, "purchaseorderId" integer, CONSTRAINT "PK_a2c68765d2cefbbbbaf92e6fa00" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_order" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" SERIAL NOT NULL, "invoiceNumber" character varying NOT NULL, "inputedinvoiceNumber" character varying, "totalcostprice" integer, "transactionstatusId" integer NOT NULL, "doctypeId" integer NOT NULL, "dueDate" TIMESTAMP NOT NULL, "postingTypeId" integer NOT NULL, "isconfirmed" boolean NOT NULL, "businesslocationId" uuid, "shipbusinesslocationId" uuid, "supplierId" uuid, "fiscalyearId" uuid, "orderpaymentId" uuid, "confirmedbyId" uuid, "businessId" uuid, CONSTRAINT "PK_ad3e1c7b862f4043b103a6c8c60" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_item" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "qty" integer NOT NULL, "cost" numeric NOT NULL, "unitprice" numeric NOT NULL, "previousqty" integer NOT NULL, "productId" uuid, "purchaseorderId" integer, CONSTRAINT "PK_d01158fe15b1ead5c26fd7f4e90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_card" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "StockMovementDescription" character varying NOT NULL, "Direction" integer NOT NULL, "Quantity" integer NOT NULL, "businesslocationId" uuid, "productId" uuid, CONSTRAINT "PK_4fbf097977601f59e44eb7e418f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fc8fa788a8128a0c6c01f3e79d" ON "stock_card" ("businesslocationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_023e24d32b48071bda0f9bc5af" ON "stock_card" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_831a09ba37eecc411d560f2e17" ON "stock_card" ("Direction") `);
        await queryRunner.query(`CREATE INDEX "IDX_93bd7d26e1de63240900871503" ON "stock_card" ("Quantity") `);
        await queryRunner.query(`CREATE TABLE "store_product" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "instockqty" integer NOT NULL, "committedqty" integer NOT NULL, "orderedqty" integer NOT NULL, "availableqty" integer NOT NULL, "businesslocationId" uuid, "productId" uuid, CONSTRAINT "PK_de6af3a8762c59860794f42d8f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ba44c296693b083792742c73c5" ON "store_product" ("businesslocationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_13e275149d7414c2694da12dcf" ON "store_product" ("productId") `);
        await queryRunner.query(`CREATE TABLE "product_configuration" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pack" integer NOT NULL, "leadtime" integer NOT NULL, "canexpire" boolean NOT NULL, "canbesold" boolean NOT NULL, "canbepurchased" boolean NOT NULL, "anypromo" boolean NOT NULL, CONSTRAINT "PK_234f05214d60c49e9a673bd7e2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "price_configuration" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "qty" integer NOT NULL, "price" integer NOT NULL, "ispromo" boolean NOT NULL, "start" TIMESTAMP NOT NULL, "end" TIMESTAMP NOT NULL, "extracolum" integer NOT NULL, "productId" uuid, CONSTRAINT "PK_cc0a28c08c385d20508c19d71cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b3beed5d4b57fd35b1dc80921b" ON "price_configuration" ("productId") `);
        await queryRunner.query(`CREATE TABLE "product" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "itemcode" character varying NOT NULL, "description" character varying NOT NULL, "imagelink" character varying NOT NULL, "categoryId" uuid, "subCategoryId" uuid, "businessId" uuid, "productconfigurationId" uuid, CONSTRAINT "REL_beb436344a3af6611cbfac22e7" UNIQUE ("productconfigurationId"), CONSTRAINT "PK_bebc9158e480b949565b4dc7a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22cc43e9a74d7498546e9a63e7" ON "product" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_a47bd591fe7cf05bec0d88a679" ON "product" ("itemcode") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff0c0301a95e517153df97f681" ON "product" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b95800811275dd98a888044d5" ON "product" ("businessId") `);
        await queryRunner.query(`CREATE TABLE "category" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "businessId" uuid, CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sub_category" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "categoryId" uuid, "businessId" uuid, CONSTRAINT "PK_59f4461923255f1ce7fc5e7423c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_transfer" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transfertype" integer NOT NULL, "businesslocationFromId" uuid, "businesslocationToId" uuid, CONSTRAINT "PK_b6165ea3cc5b8062e7eaa1bd44d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6897e007b1f7d24060183c457c" ON "stock_transfer" ("transfertype") `);
        await queryRunner.query(`CREATE INDEX "IDX_b48373f86aa3a9375fba0763d7" ON "stock_transfer" ("businesslocationFromId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3b7e00f224d2baaaa80bad4454" ON "stock_transfer" ("businesslocationToId") `);
        await queryRunner.query(`CREATE TABLE "payment_mode" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "businessId" uuid, CONSTRAINT "PK_28d86a39aa07b1ad6809174fbff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_term" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "noofdays" integer NOT NULL, "businessId" uuid, CONSTRAINT "PK_e06d6ccc9db17416919b5f46d6d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "business" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "address" character varying NOT NULL, "logoPath" character varying NOT NULL, CONSTRAINT "PK_0bd850da8dafab992e2e9b058e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "business_location" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "address" character varying NOT NULL, "businessId" uuid, CONSTRAINT "PK_3288cfb92c9598363f830e1a56b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unit_of_stock" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "PK_5960061921d6bbefcff53d4412d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "FK_29beacc87831d8b4f775e0c4057" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_user" ADD CONSTRAINT "FK_2a23ceb75c7511d0523c4aaf492" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_user" ADD CONSTRAINT "FK_89e55dae19555d0d5fe8602b281" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_premission" ADD CONSTRAINT "FK_11d81560c95f356256b89c0f27f" FOREIGN KEY ("applicationrouteId") REFERENCES "application_route"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_premission" ADD CONSTRAINT "FK_ac8e782ab0a27f3b545cdbf1bc5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_78725ac7117e7526e028014606b" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_82c748fcfda007eb5c77297373c" FOREIGN KEY ("businesslocationId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_3a92cf6add00043cef9833db1cd" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_bb98ebb1d41a945ac43aa75d9f4" FOREIGN KEY ("businesslocationId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "FK_0233f7239d820ca88cbf8271187" FOREIGN KEY ("businesslocationId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier" ADD CONSTRAINT "FK_32b6011b7ad5cb5f5096b8f7f09" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier" ADD CONSTRAINT "FK_1c6429e4b01ce139810809df29c" FOREIGN KEY ("registeredlocationId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_payment" ADD CONSTRAINT "FK_4db7c4be694446aa291e695bc0b" FOREIGN KEY ("purchaseorderId") REFERENCES "purchase_order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD CONSTRAINT "FK_e1b82a8d4458efc555463c73b87" FOREIGN KEY ("businesslocationId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD CONSTRAINT "FK_a8afceeb2a99d891e827fbd5d90" FOREIGN KEY ("shipbusinesslocationId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD CONSTRAINT "FK_e4ea5841622429c12889a487f31" FOREIGN KEY ("supplierId") REFERENCES "supplier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD CONSTRAINT "FK_de643531a0174b5dc8284ee61bc" FOREIGN KEY ("fiscalyearId") REFERENCES "fiscal_year"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD CONSTRAINT "FK_a29607c1e4d5dc5fb7a99449f07" FOREIGN KEY ("orderpaymentId") REFERENCES "purchase_order_payment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD CONSTRAINT "FK_30c5823ab097ed3bb2ff019e3ba" FOREIGN KEY ("confirmedbyId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD CONSTRAINT "FK_692d6d35b8f74bccf22f154c942" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_904370c093ceea4369659a3c810" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_3c2a4c8feebcfa37da0ea85dfab" FOREIGN KEY ("purchaseorderId") REFERENCES "purchase_order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_card" ADD CONSTRAINT "FK_fc8fa788a8128a0c6c01f3e79d9" FOREIGN KEY ("businesslocationId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_card" ADD CONSTRAINT "FK_023e24d32b48071bda0f9bc5af3" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_product" ADD CONSTRAINT "FK_ba44c296693b083792742c73c51" FOREIGN KEY ("businesslocationId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_product" ADD CONSTRAINT "FK_13e275149d7414c2694da12dcf7" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_configuration" ADD CONSTRAINT "FK_b3beed5d4b57fd35b1dc80921bc" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_ff0c0301a95e517153df97f6812" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_463d24f6d4905c488bd509164e6" FOREIGN KEY ("subCategoryId") REFERENCES "sub_category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_8b95800811275dd98a888044d50" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_beb436344a3af6611cbfac22e7b" FOREIGN KEY ("productconfigurationId") REFERENCES "product_configuration"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "FK_38a5797d0473710fb41af5a97f1" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sub_category" ADD CONSTRAINT "FK_51b8c0b349725210c4bd8b9b7a7" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sub_category" ADD CONSTRAINT "FK_99a26d343738525a71710e1b898" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" ADD CONSTRAINT "FK_b48373f86aa3a9375fba0763d76" FOREIGN KEY ("businesslocationFromId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" ADD CONSTRAINT "FK_3b7e00f224d2baaaa80bad4454a" FOREIGN KEY ("businesslocationToId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_mode" ADD CONSTRAINT "FK_868a036fe6b6d9f022fcaecca37" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_term" ADD CONSTRAINT "FK_17cd4d29823ef76a3c2f0149dd7" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_location" ADD CONSTRAINT "FK_46df66863ec4dac6a3572765220" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "business_location" DROP CONSTRAINT "FK_46df66863ec4dac6a3572765220"`);
        await queryRunner.query(`ALTER TABLE "payment_term" DROP CONSTRAINT "FK_17cd4d29823ef76a3c2f0149dd7"`);
        await queryRunner.query(`ALTER TABLE "payment_mode" DROP CONSTRAINT "FK_868a036fe6b6d9f022fcaecca37"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" DROP CONSTRAINT "FK_3b7e00f224d2baaaa80bad4454a"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" DROP CONSTRAINT "FK_b48373f86aa3a9375fba0763d76"`);
        await queryRunner.query(`ALTER TABLE "sub_category" DROP CONSTRAINT "FK_99a26d343738525a71710e1b898"`);
        await queryRunner.query(`ALTER TABLE "sub_category" DROP CONSTRAINT "FK_51b8c0b349725210c4bd8b9b7a7"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "FK_38a5797d0473710fb41af5a97f1"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_beb436344a3af6611cbfac22e7b"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_8b95800811275dd98a888044d50"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_463d24f6d4905c488bd509164e6"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_ff0c0301a95e517153df97f6812"`);
        await queryRunner.query(`ALTER TABLE "price_configuration" DROP CONSTRAINT "FK_b3beed5d4b57fd35b1dc80921bc"`);
        await queryRunner.query(`ALTER TABLE "store_product" DROP CONSTRAINT "FK_13e275149d7414c2694da12dcf7"`);
        await queryRunner.query(`ALTER TABLE "store_product" DROP CONSTRAINT "FK_ba44c296693b083792742c73c51"`);
        await queryRunner.query(`ALTER TABLE "stock_card" DROP CONSTRAINT "FK_023e24d32b48071bda0f9bc5af3"`);
        await queryRunner.query(`ALTER TABLE "stock_card" DROP CONSTRAINT "FK_fc8fa788a8128a0c6c01f3e79d9"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_3c2a4c8feebcfa37da0ea85dfab"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_904370c093ceea4369659a3c810"`);
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP CONSTRAINT "FK_692d6d35b8f74bccf22f154c942"`);
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP CONSTRAINT "FK_30c5823ab097ed3bb2ff019e3ba"`);
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP CONSTRAINT "FK_a29607c1e4d5dc5fb7a99449f07"`);
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP CONSTRAINT "FK_de643531a0174b5dc8284ee61bc"`);
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP CONSTRAINT "FK_e4ea5841622429c12889a487f31"`);
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP CONSTRAINT "FK_a8afceeb2a99d891e827fbd5d90"`);
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP CONSTRAINT "FK_e1b82a8d4458efc555463c73b87"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_payment" DROP CONSTRAINT "FK_4db7c4be694446aa291e695bc0b"`);
        await queryRunner.query(`ALTER TABLE "supplier" DROP CONSTRAINT "FK_1c6429e4b01ce139810809df29c"`);
        await queryRunner.query(`ALTER TABLE "supplier" DROP CONSTRAINT "FK_32b6011b7ad5cb5f5096b8f7f09"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "FK_0233f7239d820ca88cbf8271187"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_bb98ebb1d41a945ac43aa75d9f4"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_3a92cf6add00043cef9833db1cd"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_82c748fcfda007eb5c77297373c"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_78725ac7117e7526e028014606b"`);
        await queryRunner.query(`ALTER TABLE "user_premission" DROP CONSTRAINT "FK_ac8e782ab0a27f3b545cdbf1bc5"`);
        await queryRunner.query(`ALTER TABLE "user_premission" DROP CONSTRAINT "FK_11d81560c95f356256b89c0f27f"`);
        await queryRunner.query(`ALTER TABLE "role_user" DROP CONSTRAINT "FK_89e55dae19555d0d5fe8602b281"`);
        await queryRunner.query(`ALTER TABLE "role_user" DROP CONSTRAINT "FK_2a23ceb75c7511d0523c4aaf492"`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "FK_29beacc87831d8b4f775e0c4057"`);
        await queryRunner.query(`DROP TABLE "unit_of_stock"`);
        await queryRunner.query(`DROP TABLE "business_location"`);
        await queryRunner.query(`DROP TABLE "business"`);
        await queryRunner.query(`DROP TABLE "payment_term"`);
        await queryRunner.query(`DROP TABLE "payment_mode"`);
        await queryRunner.query(`DROP INDEX "IDX_3b7e00f224d2baaaa80bad4454"`);
        await queryRunner.query(`DROP INDEX "IDX_b48373f86aa3a9375fba0763d7"`);
        await queryRunner.query(`DROP INDEX "IDX_6897e007b1f7d24060183c457c"`);
        await queryRunner.query(`DROP TABLE "stock_transfer"`);
        await queryRunner.query(`DROP TABLE "sub_category"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP INDEX "IDX_8b95800811275dd98a888044d5"`);
        await queryRunner.query(`DROP INDEX "IDX_ff0c0301a95e517153df97f681"`);
        await queryRunner.query(`DROP INDEX "IDX_a47bd591fe7cf05bec0d88a679"`);
        await queryRunner.query(`DROP INDEX "IDX_22cc43e9a74d7498546e9a63e7"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP INDEX "IDX_b3beed5d4b57fd35b1dc80921b"`);
        await queryRunner.query(`DROP TABLE "price_configuration"`);
        await queryRunner.query(`DROP TABLE "product_configuration"`);
        await queryRunner.query(`DROP INDEX "IDX_13e275149d7414c2694da12dcf"`);
        await queryRunner.query(`DROP INDEX "IDX_ba44c296693b083792742c73c5"`);
        await queryRunner.query(`DROP TABLE "store_product"`);
        await queryRunner.query(`DROP INDEX "IDX_93bd7d26e1de63240900871503"`);
        await queryRunner.query(`DROP INDEX "IDX_831a09ba37eecc411d560f2e17"`);
        await queryRunner.query(`DROP INDEX "IDX_023e24d32b48071bda0f9bc5af"`);
        await queryRunner.query(`DROP INDEX "IDX_fc8fa788a8128a0c6c01f3e79d"`);
        await queryRunner.query(`DROP TABLE "stock_card"`);
        await queryRunner.query(`DROP TABLE "order_item"`);
        await queryRunner.query(`DROP TABLE "purchase_order"`);
        await queryRunner.query(`DROP TABLE "purchase_order_payment"`);
        await queryRunner.query(`DROP TABLE "fiscal_year"`);
        await queryRunner.query(`DROP TABLE "supplier"`);
        await queryRunner.query(`DROP TABLE "customer"`);
        await queryRunner.query(`DROP INDEX "IDX_bb98ebb1d41a945ac43aa75d9f"`);
        await queryRunner.query(`DROP INDEX "IDX_3a92cf6add00043cef9833db1c"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "user_premission"`);
        await queryRunner.query(`DROP TABLE "application_route"`);
        await queryRunner.query(`DROP TABLE "role_user"`);
        await queryRunner.query(`DROP TABLE "role"`);
    }

}
