import {MigrationInterface, QueryRunner} from "typeorm";

export class ReCreatUserTable1594378702300 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "users" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL, "createdby" character varying(300), "updatedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying(300) NOT NULL, "email" character varying(100) NOT NULL, "emailConfirmed" boolean NOT NULL, "password" character varying(300) NOT NULL, "twoFactorEnable" boolean NOT NULL, "accessFailedCount" integer NOT NULL, "firstName" character varying(300) NOT NULL, "lastName" character varying NOT NULL, "siguptoken" character varying NOT NULL, "phonenumber" character varying(15) NOT NULL, "businessId" uuid, "businesslocationId" uuid, CONSTRAINT "REL_78725ac7117e7526e028014606" UNIQUE ("businessId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "role" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "role" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "role_user" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "role_user" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "role_user" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "role_user" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "application_route" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "application_route" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "application_route" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "application_route" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "user_premission" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "user_premission" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "user_premission" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "user_premission" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "supplier" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "supplier" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "supplier" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "supplier" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "fiscal_year" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "fiscal_year" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "fiscal_year" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "fiscal_year" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "purchase_order_payment" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_payment" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "purchase_order_payment" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_payment" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "stock_card" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "stock_card" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "stock_card" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "stock_card" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "product_configuration" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "product_configuration" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "product_configuration" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "product_configuration" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "price_configuration" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "price_configuration" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "price_configuration" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "price_configuration" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "category" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "category" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "sub_category" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "sub_category" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "sub_category" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "sub_category" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "payment_mode" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "payment_mode" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "payment_mode" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "payment_mode" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "payment_term" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "payment_term" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "payment_term" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "payment_term" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "business" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "business" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "business" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "business" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "business_location" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "business_location" ADD "createdby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "business_location" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "business_location" ADD "updatedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "role_user" ADD CONSTRAINT "FK_2a23ceb75c7511d0523c4aaf492" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_premission" ADD CONSTRAINT "FK_ac8e782ab0a27f3b545cdbf1bc5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_78725ac7117e7526e028014606b" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_82c748fcfda007eb5c77297373c" FOREIGN KEY ("businesslocationId") REFERENCES "business_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD CONSTRAINT "FK_30c5823ab097ed3bb2ff019e3ba" FOREIGN KEY ("confirmedbyId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP CONSTRAINT "FK_30c5823ab097ed3bb2ff019e3ba"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_82c748fcfda007eb5c77297373c"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_78725ac7117e7526e028014606b"`);
        await queryRunner.query(`ALTER TABLE "user_premission" DROP CONSTRAINT "FK_ac8e782ab0a27f3b545cdbf1bc5"`);
        await queryRunner.query(`ALTER TABLE "role_user" DROP CONSTRAINT "FK_2a23ceb75c7511d0523c4aaf492"`);
        await queryRunner.query(`ALTER TABLE "business_location" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "business_location" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "business_location" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "business_location" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "business" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "business" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "business" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "business" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_term" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "payment_term" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_term" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "payment_term" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_mode" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "payment_mode" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_mode" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "payment_mode" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sub_category" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "sub_category" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sub_category" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "sub_category" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "category" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "category" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "product" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_configuration" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "price_configuration" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_configuration" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "price_configuration" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_configuration" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "product_configuration" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_configuration" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "product_configuration" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_card" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "stock_card" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_card" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "stock_card" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_order_payment" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_payment" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_order_payment" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_payment" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fiscal_year" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "fiscal_year" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fiscal_year" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "fiscal_year" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "supplier" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "supplier" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_premission" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "user_premission" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_premission" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "user_premission" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_route" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "application_route" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_route" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "application_route" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role_user" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "role_user" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role_user" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "role_user" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "updatedby"`);
        await queryRunner.query(`ALTER TABLE "role" ADD "updatedby" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "role" ADD "createdby" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
