import {MigrationInterface, QueryRunner} from "typeorm";

export class UpdatedStockTransfer1612269306146 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "stock_transfer_items" ("dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "dateUpdated" TIMESTAMP NOT NULL DEFAULT now(), "isDisabled" boolean NOT NULL DEFAULT true, "createdby" character varying(300), "updatedby" character varying(300), "deletedby" character varying(300), "approvedby" character varying(300), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "warehouseId" character varying NOT NULL, "qty" integer NOT NULL DEFAULT 0, "approvedqty" integer NOT NULL DEFAULT 0, "itemStatus" integer NOT NULL DEFAULT 1, "productId" uuid, CONSTRAINT "PK_8acee6121ab8a5135dc84495588" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f3d2b9e6f306fc4a292c687a12" ON "stock_transfer_items" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_12c07f8369e4e48084ebfcee73" ON "stock_transfer_items" ("warehouseId") `);
        await queryRunner.query(`ALTER TABLE "role" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "role" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "role_user" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "role_user" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "application_route" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "application_route" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "user_premission" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "user_premission" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "sales_items" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "supplier" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "supplier" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "fiscal_year" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "fiscal_year" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "purchase_order_payment" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "purchase_order_payment" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "warehouse" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "warehouse" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "stock_card" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "stock_card" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "tax" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "tax" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "product_configuration" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "product_configuration" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "price_configuration" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "price_configuration" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "product" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "product" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "category" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "category" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "sub_category" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "sub_category" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "payment_mode" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "payment_mode" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "payment_term" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "payment_term" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "business" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "business" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "business_location" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "business_location" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "price_audit_log" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "price_audit_log" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" ADD "deletedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" ADD "approvedby" character varying(300)`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" ADD "note" character varying NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" ADD "status" integer NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" ADD CONSTRAINT "FK_f3d2b9e6f306fc4a292c687a12d" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "stock_transfer_items" DROP CONSTRAINT "FK_f3d2b9e6f306fc4a292c687a12d"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "price_audit_log" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "price_audit_log" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "business_location" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "business_location" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "business" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "business" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "payment_term" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "payment_term" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "payment_mode" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "payment_mode" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "sub_category" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "sub_category" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "product" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "price_configuration" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "price_configuration" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "product_configuration" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "product_configuration" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "tax" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "tax" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "stock_card" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "stock_card" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "warehouse" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "warehouse" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_payment" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_payment" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "fiscal_year" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "fiscal_year" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "supplier" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "supplier" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "sales_items" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "user_premission" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "user_premission" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "application_route" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "application_route" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "role_user" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "role_user" DROP COLUMN "deletedby"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "approvedby"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "deletedby"`);
        await queryRunner.query(`DROP INDEX "IDX_12c07f8369e4e48084ebfcee73"`);
        await queryRunner.query(`DROP INDEX "IDX_f3d2b9e6f306fc4a292c687a12"`);
        await queryRunner.query(`DROP TABLE "stock_transfer_items"`);
    }

}
